# Generated by Django 5.1.3 on 2024-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listalbum',
            options={'ordering': ['rank']},
        ),
        migrations.AlterUniqueTogether(
            name='listalbum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listalbum',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listalbum',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='listalbum',
            name='added_at',
        ),
    ]
